const state = { projects: JSON.parse(localStorage.getItem('veclite-projects') || '[]'), activeId: localStorage.getItem('veclite-active-project'), stores: [], documentPage: 0 };
const $ = (id) => document.getElementById(id);
const projectDialog = $('project-dialog'), storeDialog = $('store-dialog');

function activeProject() { return state.projects.find((project) => project.id === state.activeId); }
function saveProjects() { localStorage.setItem('veclite-projects', JSON.stringify(state.projects)); localStorage.setItem('veclite-active-project', state.activeId || ''); }
function apiPath(path) { const project = activeProject(); if (!project) throw new Error('请先选择一个项目'); return `${project.url.replace(/\/$/, '')}${path}`; }
async function request(path, options = {}) { const response = await fetch(apiPath(path), { headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const text = await response.text(); if (!response.ok) throw new Error(text || `请求失败（HTTP ${response.status}）`); if (!text) return null; try { return JSON.parse(text); } catch (_) { return text; } }
function toast(message, error = false) { const node = $('toast'); node.textContent = message; node.className = `toast show${error ? ' error' : ''}`; clearTimeout(toast.timer); toast.timer = setTimeout(() => { node.className = 'toast'; }, 3000); }
function setStatus(text, kind = 'idle') { const node = $('connection-status'); node.textContent = text; node.className = `status ${kind}`; }
function renderProjects() { const project = activeProject(); $('project-list').innerHTML = state.projects.map((item) => `<button class="project-item ${item.id === state.activeId ? 'active' : ''}" data-project="${item.id}">${escapeHtml(item.name)}<small>${escapeHtml(item.url)}</small></button>`).join(''); $('project-title').textContent = project ? project.name : '未选择项目'; $('project-url').textContent = project ? project.url : '请添加一个使用 Veclite SDK 的 Spring Boot 项目。'; $('edit-project').disabled = !project; $('empty-state').hidden = !!project; $('workspace').hidden = !project; document.querySelectorAll('[data-project]').forEach((node) => node.addEventListener('click', () => { state.activeId = node.dataset.project; saveProjects(); renderProjects(); loadStores(); })); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
async function loadStores() { if (!activeProject()) return; setStatus('连接中…'); try { state.stores = await request('/stores'); const select = $('store-select'); const previous = select.value; select.innerHTML = '<option value="">选择向量库</option>' + state.stores.map((name) => `<option value="${escapeHtml(name)}">${escapeHtml(name)}</option>`).join(''); if (state.stores.includes(previous)) select.value = previous; setStatus('已连接', 'connected'); await loadStats(); } catch (error) { state.stores = []; setStatus('连接失败', 'error'); $('store-select').innerHTML = '<option value="">无法加载向量库</option>'; $('stats-panel').hidden = true; toast(`无法连接：${error.message}`, true); } }
async function loadStats() { const store = $('store-select').value; if (!store) { $('stats-panel').hidden = true; return; } try { const stats = await request(`/stores/${encodeURIComponent(store)}/stats`); const fields = [['文档数量', stats.docCount], ['向量维度', stats.dimension], ['最大容量', stats.maxCapacity], ['距离度量', stats.metric], ['量化', stats.quantization]]; $('stats-panel').innerHTML = fields.map(([label, value]) => `<div class="stat"><span>${label}</span><strong>${escapeHtml(value)}</strong></div>`).join(''); $('stats-panel').hidden = false; } catch (error) { toast(`无法读取统计信息：${error.message}`, true); } }
async function loadDocuments(page = state.documentPage) { const store = $('store-select').value; const list = $('document-list'), pagination = $('document-pagination'); if (!store) { list.className = 'results muted'; list.textContent = '选择向量库后查看已写入的文档。'; pagination.hidden = true; return; } try { const data = await request(`/stores/${encodeURIComponent(store)}/documents?page=${page}&size=20`); state.documentPage = data.page; const pageCount = Math.ceil(data.total / data.size); $('document-page-summary').textContent = `共 ${data.total} 条文档，每页 ${data.size} 条`; list.className = 'results'; list.innerHTML = data.items.length ? data.items.map((document) => `<article class="result"><div><div class="result-title">${escapeHtml(document.id)}</div><div class="result-text">${escapeHtml(document.text || '—')}</div><div class="metadata">${escapeHtml(JSON.stringify(document.metadata || {}))}</div></div><button class="button button-danger delete-document" data-id="${escapeHtml(document.id)}">删除</button></article>`).join('') : '<div class="muted">这一页没有文档。</div>'; pagination.hidden = data.total === 0; $('document-page-number').textContent = `第 ${data.page + 1} / ${Math.max(pageCount, 1)} 页`; $('previous-document-page').disabled = data.page === 0; $('next-document-page').disabled = data.page + 1 >= pageCount; document.querySelectorAll('.delete-document').forEach((node) => node.addEventListener('click', () => deleteDocument(node.dataset.id))); } catch (error) { list.className = 'results muted'; list.textContent = `无法读取文档：${error.message}`; pagination.hidden = true; } }
function currentStore() { const store = $('store-select').value; if (!store) { toast('请先选择向量库', true); return null; } return store; }
function parseVector(value) { const vector = value.split(',').map((part) => Number(part.trim())).filter((number) => !Number.isNaN(number)); if (!vector.length) throw new Error('请填写有效的逗号分隔向量'); return vector; }
function openProjectDialog(edit = false) { const project = activeProject(); $('project-dialog-title').textContent = edit ? '编辑项目' : '添加项目'; $('project-name').value = edit ? project.name : ''; $('project-api-url').value = edit ? project.url : ''; projectDialog.showModal(); }
$('add-project').addEventListener('click', () => openProjectDialog()); $('empty-add-project').addEventListener('click', () => openProjectDialog()); $('edit-project').addEventListener('click', () => openProjectDialog(true)); $('cancel-project').addEventListener('click', () => projectDialog.close());
$('project-form').addEventListener('submit', async (event) => { event.preventDefault(); const name = $('project-name').value.trim(), url = $('project-api-url').value.trim().replace(/\/$/, ''); if (!name || !url) return; const existing = activeProject(); const project = existing ? { ...existing, name, url } : { id: crypto.randomUUID(), name, url }; if (existing) state.projects = state.projects.map((item) => item.id === project.id ? project : item); else { state.projects.push(project); state.activeId = project.id; } saveProjects(); projectDialog.close(); renderProjects(); await loadStores(); });
$('store-select').addEventListener('change', () => { state.documentPage = 0; loadStats(); loadDocuments(); }); $('reload-stores').addEventListener('click', loadStores); $('reload-documents').addEventListener('click', () => loadDocuments()); $('previous-document-page').addEventListener('click', () => loadDocuments(state.documentPage - 1)); $('next-document-page').addEventListener('click', () => loadDocuments(state.documentPage + 1)); $('new-store').addEventListener('click', () => storeDialog.showModal()); $('cancel-store').addEventListener('click', () => storeDialog.close());
$('store-form').addEventListener('submit', async (event) => { event.preventDefault(); const name = $('store-name').value.trim(); try { await request(`/stores/${encodeURIComponent(name)}`, { method:'POST', body:JSON.stringify({ storeName:name, dimension:Number($('store-dimension').value), metric:$('store-metric').value, maxCapacity:Number($('store-capacity').value), quantization:$('store-quantization').value, indexedMetadataFields:[] }) }); storeDialog.close(); await loadStores(); $('store-select').value = name; state.documentPage = 0; await loadStats(); await loadDocuments(); toast('向量库已创建'); } catch (error) { toast(`创建失败：${error.message}`, true); } });
$('upsert-form').addEventListener('submit', async (event) => { event.preventDefault(); const store = currentStore(); if (!store) return; try { const metadataText = $('document-metadata').value.trim(), vectorText = $('document-vector').value.trim(); await request(`/stores/${encodeURIComponent(store)}/documents`, { method:'POST', body:JSON.stringify({ id:$('document-id').value.trim(), text:$('document-text').value.trim() || null, vector:vectorText ? parseVector(vectorText) : null, metadata:metadataText ? JSON.parse(metadataText) : {} }) }); $('upsert-form').reset(); await loadStats(); await loadDocuments(); toast('文档已写入'); } catch (error) { toast(`写入失败：${error.message}`, true); } });
$('search-mode').addEventListener('change', () => { $('search-query').placeholder = $('search-mode').value === 'vector' ? '0.1, 0.2, 0.3' : '输入用于语义检索的文本'; });
$('search-form').addEventListener('submit', async (event) => { event.preventDefault(); const store = currentStore(); if (!store) return; try { const mode = $('search-mode').value, query = $('search-query').value.trim(), body = { topK:Number($('search-top-k').value) }; if (mode === 'vector') body.queryVector = parseVector(query); else body.queryText = query; const results = await request(`/stores/${encodeURIComponent(store)}/search/${mode}`, { method:'POST', body:JSON.stringify(body) }); $('search-results').className = 'results'; $('search-results').innerHTML = results.length ? results.map((result) => `<article class="result"><div><div class="result-title">${escapeHtml(result.id)}</div><div class="result-text">${escapeHtml(result.text || '—')}</div><div class="metadata">${escapeHtml(JSON.stringify(result.metadata || {}))}</div></div><div><div class="score">${Number(result.score).toFixed(5)}</div><button class="button button-danger delete-document" data-id="${escapeHtml(result.id)}">删除</button></div></article>`).join('') : '<div class="muted">没有匹配结果。</div>'; document.querySelectorAll('.delete-document').forEach((node) => node.addEventListener('click', () => deleteDocument(node.dataset.id))); } catch (error) { toast(`检索失败：${error.message}`, true); } });
async function deleteDocument(id) { const store = currentStore(); if (!store || !confirm(`删除文档 ${id}？`)) return; try { await request(`/stores/${encodeURIComponent(store)}/documents`, { method:'DELETE', body:JSON.stringify([id]) }); toast('文档已删除'); await loadStats(); await loadDocuments(); } catch (error) { toast(`删除失败：${error.message}`, true); } }
$('refresh-store').addEventListener('click', async () => { const store = currentStore(); if (!store) return; try { await request(`/stores/${encodeURIComponent(store)}/refresh`, { method:'POST' }); toast('已请求持久化'); } catch (error) { toast(`操作失败：${error.message}`, true); } });
$('delete-store').addEventListener('click', async () => { const store = currentStore(); if (!store || !confirm(`永久删除向量库 ${store}？`)) return; try { await request(`/stores/${encodeURIComponent(store)}`, { method:'DELETE' }); toast('向量库已删除'); await loadStores(); } catch (error) { toast(`删除失败：${error.message}`, true); } });
renderProjects(); if (activeProject()) loadStores();
